#!/usr/bin/env bash
# Prints numbers from 1 to 100 in list format.
# Prints "FizzBuzz" when the number is a multiple of 3 and 5.
# Prints "Fizz" when the number is a multiple of 3.
# Prints "Buzz" when the number is a multiple of 5.
# Else, prints the number.

for n in {1..100}
do
  if (( n % 3 == 0 && n % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( n % 3 == 0 ))
  then
    echo "Fizz"
  elif (( n % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$n"
  fi
done
