#!/usr/bin/env bash
# this prints "Best School" 10 times using while loop.
# and print "Hi" befor "Best School" on the 9th iteration.

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done

