#!/usr/bin/env bash
# Loops from 1 to 10 and prints:
#   "bad luck" on the 4th iteration
#   "good luck" on the 8th iteration
#   "Best School" on every other iterations

counter=0

while [ $counter -lt 10 ]
do
  if [ $counter -eq 3 ]
  then
    echo "bad luck"
  elif [ $counter -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( counter++ ))
done
