#!/usr/bin/env bash
# Prints the contents of the present directory in list format.
# Prints the part of the name after the first dash. 

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
